-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Vesisto CASCADE;

DROP TABLE IF EXISTS Naytteenottopaikka CASCADE;

DROP TABLE IF EXISTS Tutkimusaihe CASCADE;

DROP TABLE IF EXISTS Vesistotutkimus CASCADE;

DROP TABLE IF EXISTS Tutkimusohje CASCADE;

DROP TABLE IF EXISTS Kenttamittaus CASCADE;

DROP TABLE IF EXISTS Kenttamittaus CASCADE;

DROP TABLE IF EXISTS Nayte CASCADE;

DROP TABLE IF EXISTS Tulos CASCADE;


);